### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Guenni9** [DeerMaximum/Technische-Alternative-CMI#7] opened 2022-10-25 06:28 UTC
## Version of the custom_component
1.0

## Describe the bug
Installation as described not possible, unknown error occurs. 

![image](https://user-images.githubusercontent.com/101923813/197690948-db6ce98f-380d-4bfe-8ea2-60a6f92f5bb9.png)

Connection to the CMI works. If e.g. giving wrong credentials, an authentication error occurs. With correct credentials, after about one minute the above posted screen appears.

And calling the API with a browser with e.g. `http://192.168.0.13/INCLUDE/api.cgi?jsonnode=1&jsonparam=I,O`, parameters are given well:

`{ "Header":{ "Version":6, "Device":"8C", "Timestamp":1666686007 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":26.0, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":75.0, "Unit":"8" } }, { "Number":3, "AD":"A", "Value":{ "Value":21.1, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":0.0, "Unit":"65" } }, { "Number":5, "AD":"A", "Value":{ "Value":0, "Unit":"67" } }, { "Number":6, "AD":"A", "Value":{ "Value":18.2, "Unit":"52" } }]}, "Status":"OK", "Status code":0 }`

Any ideas, how to catch the error? If futher informations are needed, please let me know.

Thank You for support and for the integration!
Günter

## Debug log
`Logger: aiohttp.server
Source: custom_components/ta_cmi/config_flow.py:137
Integration: Technische Alternative C.M.I. ([documentation](https://github.com/DeerMaximum/Technische-Alternative-CMI), [issues](https://github.com/DeerMaximum/Technische-Alternative-CMI/issues))
First occurred: 07:57:45 (3 occurrences)
Last logged: 08:10:57

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ta_cmi/config_flow.py", line 94, in async_step_user
    return await self.async_step_devices()
  File "/config/custom_components/ta_cmi/config_flow.py", line 137, in async_step_devices
    await dev.update()
  File "/usr/local/lib/python3.10/site-packages/ta_cmi/device.py", line 48, in update
    self.outputs: Dict[int, Channel] = self._extractChannels(ChannelMode.OUTPUT, res["Data"]["Outputs"])
KeyError: 'Outputs'`

**Comment by hauptmj** [comment] 2022-10-25 14:20
I have the same error.

**Comment by DeerMaximum** [comment] 2022-10-25 15:02
It looks like there is a new CMI API version (6). I still need to update my CMI and see what has changed.

**Comment by DeerMaximum** [comment] 2022-10-25 16:48
@Guenni9 Your API snippet shows only inputs. Do you also have outputs on your device?

**Comment by hauptmj** [comment] 2022-10-25 19:08
My output looks like this:

{ "Header":{ "Version":6, "Device":"80", "Timestamp":1666727752 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":21.8, "Unit":"1" } } , { "Number":2, "AD":"A", "Value":{ "Value":23.5, "Unit":"1" } } , { "Number":3, "AD":"A", "Value":{ "Value":21.2, "Unit":"1" } } , { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":5, "AD":"A", "Value":{ "Value":26.0, "Unit":"1" } } , { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":7, "AD":"A", "Value":{ "Value":4.7, "Unit":"1" } } , { "Number":8, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":10, "AD":"A", "Value":{ "Value":23.1, "Unit":"1" } } , { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":12, "AD":"D", "Value":{ "Value":1, "Unit":"43" } } , { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":14, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":15, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } , { "Number":16, "AD":"D", "Value":{ "Value":0, "Unit":"43" } } ], "Outputs":[ { "Number":1, "AD":"A", "Value":{ "State":0,"Value":0, "Unit":"0" } } , { "Number":2, "AD":"A", "Value":{ "State":0,"Value":0, "Unit":"0" } } , { "Number":3, "AD":"D", "Value":{ "Value":1, "Unit":"0" } } , { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":6, "AD":"A", "Value":{ "State":0,"Value":0, "Unit":"0" } } , { "Number":7, "AD":"A", "Value":{ "State":0,"Value":0, "Unit":"0" } } , { "Number":8, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":9, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":10, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":12, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } , { "Number":13, "AD":"D", "Value":{ "Value":0, "Unit":"0" } } ]}, "Status":"OK", "Status code":0 }

**Comment by Guenni9** [comment] 2022-10-26 05:21
In my post, I've adressed Node 1, this has been my CAN MTx, there are no outputs. Sorry for this. My first thought was, because Node 1 is my CMI themself, maybe caused the error. So I've changed the nodes only for testing.

Here is the request from Node 2, a UVR 16x2:
`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=2&jsonparam=I,O`:

`{ "Header":{ "Version":6, "Device":"87", "Timestamp":1666767833 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":10.7, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":10.5, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":28.7, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":29.5, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":27.4, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":27.1, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":23.7, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":24.8, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":27.1, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":39.3, "Unit":"1" } }, { "Number":11, "AD":"A", "Value":{ "Value":30.1, "Unit":"1" } }, { "Number":12, "AD":"A", "Value":{ "Value":27.1, "Unit":"1" } }, { "Number":13, "AD":"A", "Value":{ "Value":33.5, "Unit":"1" } }, { "Number":14, "AD":"A", "Value":{ "Value":32.7, "Unit":"1" } }, { "Number":15, "AD":"A", "Value":{ "Value":9.4, "Unit":"1" } }, { "Number":16, "AD":"A", "Value":{ "Value":20.5, "Unit":"1" } }], "Outputs":[ { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }, { "Number":13, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }, { "Number":15, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":16, "AD":"A", "Value":{ "State":1, "Value":10.00, "Unit":"13" } }]}, "Status":"OK", "Status code":0 }`

**Comment by DeerMaximum** [comment] 2022-10-26 19:11
Can you try it again with the latest version(1.0.1)?

**Comment by Guenni9** [comment] 2022-10-27 06:36
Found some interesting things...

My CMI is node 1, in this case installation isn't possible. This is my setup with all TA devices:
![image](https://user-images.githubusercontent.com/101923813/198207642-be817cca-5c3f-4823-91b4-035ddcf71928.png)
Using this config, installation isn't possible:
![image](https://user-images.githubusercontent.com/101923813/198207855-78936210-694a-4c97-ad5c-57ef074b6a2d.png)


Setting CMI to node 56 and setting my UVR16x2 to node 1, installation works, there is also an unknown error.
It works, sensors are available, but only for the UVR16x2, all other devices aren't recognized:
![image](https://user-images.githubusercontent.com/101923813/198206491-cd26f5ef-e791-464d-81eb-4c67af80be36.png)


In the error-log, I found:

Logger: custom_components.ta_cmi
Source: custom_components/ta_cmi/config_flow.py:137
Integration: Technische Alternative C.M.I. ([documentation](https://github.com/DeerMaximum/Technische-Alternative-CMI), [issues](https://github.com/DeerMaximum/Technische-Alternative-CMI/issues))
First occurred: 08:11:09 (1 occurrences)
Last logged: 08:11:09

Unexpected exception: Unknown error
Traceback (most recent call last):
  File "/config/custom_components/ta_cmi/config_flow.py", line 137, in async_step_devices
    await dev.update()
  File "/usr/local/lib/python3.10/site-packages/ta_cmi/device.py", line 44, in update
    res: Dict[str, Any] = await self._make_request(url)
  File "/usr/local/lib/python3.10/site-packages/ta_cmi/baseApi.py", line 41, in _make_request
    raise ApiError("Unknown error")
ta_cmi.baseApi.ApiError: Unknown error


Let me know, if I can provide further informations..

**Comment by DeerMaximum** [comment] 2022-10-27 14:09
With the CMI as node 1, what is your output of http://CMI_IP/INCLUDE/can_nodes.cgi?_=1

**Comment by Guenni9** [comment] 2022-10-27 14:25
`http://192.168.0.13/INCLUDE/can_nodes.cgi?_=1`:

`2;3;4;5;8;`

**Comment by DeerMaximum** [comment] 2022-10-27 18:52
The Unknown error occurs when the inputs and outputs are retrieved from the devices. It appears that a node is returning an invalid status code. Can you send me responses from http://IP/INCLUDE/api.cgi?jsonnode=NODE&jsonparam=I,O from all your nodes?

**Comment by Guenni9** [comment] 2022-10-28 05:31
I found out, if retrieving my C.M.I with node 1, I get 
_"NODE ERROR", "Status code 1"_ 
But shouldn't the CMI response at least with 
_"DEVICE NOT SUPPORTED" "Status code: 5" ?_ 
Maybe this could be the problem? Could anybody check, if it's the same at their CMI?

@DeerMaximum here are all my nodes:

`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=1&jsonparam=I,O` , the CMI shows:
`{ "Header":{ "Version":6, "Device":"00", "Timestamp":1666940056 }, "Data":{ }, "Status":"NODE ERROR", "Status code":1 }`

`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=2&jsonparam=I,O` , the UVR16X2 shows:
`{"Header":{ "Version":6, "Device":"87", "Timestamp":1666940099 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":12.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":12.5, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":28.7, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":29.2, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":27.3, "Unit":"1" } }, { "Number":6, "AD":"A", "Value":{ "Value":27.1, "Unit":"1" } }, { "Number":7, "AD":"A", "Value":{ "Value":29.5, "Unit":"1" } }, { "Number":8, "AD":"A", "Value":{ "Value":28.9, "Unit":"1" } }, { "Number":9, "AD":"A", "Value":{ "Value":27.1, "Unit":"1" } }, { "Number":10, "AD":"A", "Value":{ "Value":40.5, "Unit":"1" } }, { "Number":11, "AD":"A", "Value":{ "Value":30.3, "Unit":"1" } }, { "Number":12, "AD":"A", "Value":{ "Value":27.1, "Unit":"1" } }, { "Number":13, "AD":"A", "Value":{ "Value":30.2, "Unit":"1" } }, { "Number":14, "AD":"A", "Value":{ "Value":28.0, "Unit":"1" } }, { "Number":15, "AD":"A", "Value":{ "Value":11.9, "Unit":"1" } }, { "Number":16, "AD":"A", "Value":{ "Value":20.4, "Unit":"1" } }], "Outputs":[ { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":10, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":11, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":12, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }, { "Number":13, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }, { "Number":15, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":16, "AD":"A", "Value":{ "State":1, "Value":10.00, "Unit":"13" } }]}, "Status":"OK", "Status code":0 }`

`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=3&jsonparam=I,O` ,the UVR610MODB, shows:
`{ "Header":{ "Version":6, "Device":"91", "Timestamp":1666940152 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":47.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":30.8, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":31.6, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":27.6, "Unit":"1" } }, { "Number":5, "AD":"A", "Value":{ "Value":29.5, "Unit":"1" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":2, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":3, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":6, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":7, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":8, "AD":"A", "Value":{ "State":0, "Value":0.00, "Unit":"13" } }, { "Number":9, "AD":"A", "Value":{ "State":1, "Value":3.10, "Unit":"13" } }, { "Number":10, "AD":"A", "Value":{ "State":1, "Value":100.0, "Unit":"8" } }]}, "Status":"OK", "Status code":0 }`

`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=4&jsonparam=I,O` , first CAN I/O45 shows:
`{ "Header":{ "Version":6, "Device":"89", "Timestamp":1666940258 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":40.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":37.6, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":51.1, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":42, "Unit":"3" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":1, "Unit":"43" } }, { "Number":5, "AD":"A", "Value":{ "State":0, "Value":0.0, "Unit":"8" } }]}, "Status":"OK", "Status code":0 }`

`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=5&jsonparam=I,O` , second CAN I/O 45 shows:
`{ "Header":{ "Version":6, "Device":"89", "Timestamp":1666940325 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":12.8, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":30.2, "Unit":"1" } }, { "Number":3, "AD":"A", "Value":{ "Value":20.9, "Unit":"1" } }], "Outputs":[ { "Number":1, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":4, "AD":"D", "Value":{ "Value":0, "Unit":"43" } }, { "Number":5, "AD":"A", "Value":{ "State":0, "Value":1.00, "Unit":"13" } }]}, "Status":"OK", "Status code":0 }`

`http://192.168.0.13/INCLUDE/api.cgi?jsonnode=8&jsonparam=I,O` , the CAN MTx shows:
`{ "Header":{ "Version":6, "Device":"8C", "Timestamp":1666940374 }, "Data":{ "Inputs":[ { "Number":1, "AD":"A", "Value":{ "Value":26.5, "Unit":"1" } }, { "Number":2, "AD":"A", "Value":{ "Value":73.5, "Unit":"8" } }, { "Number":3, "AD":"A", "Value":{ "Value":21.3, "Unit":"1" } }, { "Number":4, "AD":"A", "Value":{ "Value":0.0, "Unit":"65" } }, { "Number":5, "AD":"A", "Value":{ "Value":0, "Unit":"67" } }, { "Number":6, "AD":"A", "Value":{ "Value":18.4, "Unit":"52" } }]}, "Status":"OK", "Status code":0 }`

**Comment by DeerMaximum** [comment] 2022-10-28 20:51
> I found out, if retrieving my C.M.I with node 1, I get
"NODE ERROR", "Status code 1"
But shouldn't the CMI response at least with
"DEVICE NOT SUPPORTED" "Status code: 5" ?
Maybe this could be the problem? Could anybody check, if it's the same at their CMI?

No, that is not the problem. My output from the CMI has the same code.

I have released a dev version(dev-1.0.2.1) which hopefully gives us a little more information about the error. If you could test it with this version and send me the debug log, that would help further.

**Comment by Guenni9** [comment] 2022-10-29 07:09
Tried the dev, don't know why, but now it works... Takes a long time to load, but all devices are visible... And after restarting Home Assistant, it also takes very long, to get TA CMI ready..
![image](https://user-images.githubusercontent.com/101923813/198818119-49bbd7f4-2d91-40f1-8a7f-999a23227791.png)

Would you let me know, where to find the debug log? 
I've added  
_logger:
  default: info
  logs:
    custom_components.ta_cmi: debug_

**Comment by DeerMaximum** [comment] 2022-10-29 15:19
You can find the debug log in the normal log messages. 

The loading takes so long because you can send only one request per minute to the CMI. That's why the integration waits for 61 seconds between requests.

But since the problem is fixed I will close the issue, if you have more questions feel free to open it again.

**Closed by DeerMaximum** 2022-10-29 15:19 UTC
